[#7] UI Menu Component
skwirowski/CodersCamp2020.Project.JavaScript.StarWarsQuiz pull request #27
Opened 2020-12-31 11:07 UTC by GoraJakub

Please review. I believe there's many mistakes to fix.

2020-12-31 12:05 UTC, mfrydrychowicz requested changes

2020-12-31 12:05 UTC, mfrydrychowicz commented on src/app/components/mainMenu.js
> +    const buttons = [
I think you may split this function into smaller parts
eg.
createButtons () {
// creatung buttons
return buttons
}

2020-12-31 12:05 UTC, mfrydrychowicz commented on test/mainMenu.test.js
> +import {mainMenu} from '../src/app/components/mainMenu';
please run `npm run format`

2020-12-31 12:05 UTC, mfrydrychowicz commented on src/app/App.js
> +    mainMenu(document.body,getData);
Shouldn't it be : 
    `mainMenu(document.querySelector('.swquiz-header'),getData);`

and then: 
remove `flex-wrap: wrap;` from style .swquiz-header in file gameHeader.css beacuse it render wrong right now (my bad!)

2020-12-31 14:02 UTC, budnickip commented on package.json
> +    "components": "^0.1.0",
i agree with @mfrydrychowicz

2021-01-02 19:02 UTC, mfrydrychowicz requested changes

2021-01-02 19:02 UTC, mfrydrychowicz commented on src/app/components/mainMenu.js
> +  const btnPeople = createButton('swquiz-menu-button', 'People', callback);
could you import variables from modes.js and use them instead of hardcoding? That would be pro 😃

2021-01-02 19:31 UTC, budnickip approved these changes
Like Małgorzata says, if you have time, you can import consts from modes.js

2021-01-03 17:07 UTC, mfrydrychowicz submitted a review, later dismissed

2021-01-03 22:36 UTC, budnickip approved these changes

2021-01-04 08:37 UTC, merged