[#6] Checking Correct Answers
skwirowski/CodersCamp2020.Project.JavaScript.StarWarsQuiz pull request #31
Opened 2020-12-31 12:10 UTC by GoraJakub

Please review.

2020-12-31 12:34 UTC, mfrydrychowicz commented on src/app/components/isAnswerCorrect.js
> +const isAnswerCorrect = (guess,correct) =>{
Consider changing name of second param, as `correct` (for me) is more like result of comparison, rather than correct answer
```suggestion
const isAnswerCorrect = (guess, answer) =>{
```

2020-12-31 12:47 UTC, GoraJakub commented on src/app/components/isAnswerCorrect.js
> +const isAnswerCorrect = (guess,correct) =>{
Good point, thanks!

2020-12-31 12:58 UTC, mfrydrychowicz submitted a review, later dismissed
ok

2020-12-31 14:15 UTC, budnickip submitted a review, later dismissed

2020-12-31 17:06 UTC, budnickip approved these changes

2020-12-31 17:33 UTC, mfrydrychowicz commented on src/app/components/isAnswerCorrect.js
> +        throw new Error("Guessed answer isn't string");
Sorry to bother, but this could be narrowed to TypeError

2021-01-01 15:21 UTC, GoraJakub commented
Could someone approve again? Please

2021-01-02 18:54 UTC, mfrydrychowicz commented on src/app/components/isAnswerCorrect.js
> +        throw new Error("Guessed answer isn't string");
Yes / no/ maybe?

2021-01-03 22:37 UTC, budnickip approved these changes

2021-01-04 19:50 UTC, GoraJakub commented on src/app/components/isAnswerCorrect.js
> +        throw new Error("Guessed answer isn't string");
Of course!

2021-01-04 19:59 UTC, mfrydrychowicz requested changes

2021-01-04 19:59 UTC, mfrydrychowicz commented on src/app/components/isAnswerCorrect.js
> +        throw new Error("TypeError");
```suggestion
        throw new TypeError("Guessed answer isn't string");
```

See docs for more info https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError

2021-01-04 19:59 UTC, mfrydrychowicz commented on src/app/components/isAnswerCorrect.js
> +        throw new Error("TypeError");
```suggestion
       throw new TypeError("Correct answer isn't string");
```

2021-01-04 19:59 UTC, mfrydrychowicz commented on test/isAnswerCorrect.test.js
> +    expect(function(){isAnswerCorrect(foo,"answer");}).toThrow(new Error("TypeError"));
```suggestion
    expect(function(){isAnswerCorrect(foo,"answer");}).toThrow(new TypeError("Guessed answer isn't string"));
```

2021-01-04 19:59 UTC, mfrydrychowicz commented on test/isAnswerCorrect.test.js
> +    expect(function(){isAnswerCorrect("guess",foo);}).toThrow(new Error("TypeError"));
```suggestion
    expect(function(){isAnswerCorrect("guess",foo);}).toThrow(new TypeError("Correct answer isn't string"));
```

2021-01-04 20:03 UTC, mfrydrychowicz commented on src/app/App.js
> +import { isAnswerCorrect } from "./components/isAnswerCorrect";
inconsistent import style between imports
" -> '

2021-01-05 08:25 UTC, GoraJakub reviewed
Thanks for the tips

2021-01-05 15:28 UTC, mfrydrychowicz approved these changes
lgtm

2021-01-06 11:11 UTC, merged