[#13] White button with icon
skwirowski/CodersCamp2020.Project.JavaScript.StarWarsQuiz pull request #48
Opened 2021-01-02 22:18 UTC by aleksandraj036

please review

2021-01-03 12:22 UTC, budnickip reviewed
I don't see tests, so we couldn't accept your pull request.

2021-01-03 12:22 UTC, budnickip commented on index.html
> +</div>
we have to add new components like buttons only with javascript, and we shouldn't edit .html file. I think we should talk about this in next meeting, and change this assumption. If we will make this with .html it will be easier to style our app. As i can see, you add this button to DOM with function appendChild in your .js file. So your app should works without changes in .html

2021-01-03 12:22 UTC, budnickip commented on styles/App.css
> +}
I think you should add new .css file to new styles and import them to App.css with @import 
In my opinion in App.css we should only import other styles.

2021-01-08 20:17 UTC, mfrydrychowicz requested changes

2021-01-08 20:17 UTC, mfrydrychowicz commented on src/app/App.js
> +    //whiteButton('static/assets/icons/school_24px.png','Rules');
leftover - to remove

2021-01-08 20:17 UTC, mfrydrychowicz commented on styles/App.css
> +    color: black;
inconsistency. Once hex value, once literal value. Check if App.scss has desired colors, if not define them there and use as following:
background-color: var(--base-white);

2021-01-08 20:17 UTC, mfrydrychowicz commented on styles/App.css
> +}
shouldn't it be .button--white::first-letter ?

2021-01-16 13:04 UTC, closed without merging