[#50][#51] skeleton and base layout
skwirowski/CodersCamp2020.Project.JavaScript.StarWarsQuiz pull request #53
Opened 2021-01-05 09:57 UTC by budnickip

2021-01-05 15:30 UTC, mfrydrychowicz approved these changes

2021-01-06 11:51 UTC, mfrydrychowicz requested changes

2021-01-06 11:51 UTC, mfrydrychowicz commented on index.html
> -        </a>
I would leave this as it was. It is constant view for all view. Other may change and I think it would be easier to maintain it this way. Later we will have to change body of the application depending of what user had clicked.
Thus it is better to leave header class="swquiz-header" bar at the top, and then do application body class="swquiz-body".

I have a task to position the view, so I will think how to arrange the columns to keep the size. Newertheless I suggest to keep layout like that

```
<div id="swquiz-app">
    <div class="swquiz-header">
     ...
    </div>
    <div class="swquiz-body">
     ...
    </div>
</div>
```

2021-01-08 09:08 UTC, Ryczko commented on index.html
> +    <link rel="stylesheet" href="styles/App.scss"/>
I think that if we have to use scss, we shouldn't attach this in this way. https://stackoverflow.com/questions/19215517/attaching-a-sass-scss-to-html-docs
if we have to use this we should attached complied css file

2021-01-08 09:41 UTC, Ryczko commented on index.html
> -        </a>
I also think it should look like what Małgorzata says. Every other components should generating in js files

2021-01-08 19:23 UTC, closed without merging